import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import SectionHeader from "../components/SectionHeader";
import Socials from "../components/Socials";
import WhatIDo from "../components/WhatIDo/WhatIDo";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <>
            <Head>
                <title>nico.so</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <div className={styles.container}>
                <main className={styles.main}>
                    <Hero />
                </main>
            </div>
        </>
    );
}
