import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import SectionHeader from "../components/SectionHeader";
import Socials from "../components/Socials";
import WhatIDo from "../components/WhatIDo/WhatIDo";
import styles from "../styles/Home.module.css";

export default function Home(props: { name: string }) {
    console.log(props);
    return (
        <>
            <Head>
                <title>nico.so</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.container}>
                <main className={styles.main}>
                    <Hero />
                </main>
            </div>
        </>
    );
}

async function fetchBitcoinMetaData(currency: string) {
    const res = await fetch(
        "https://api.coindesk.com/v1/bpi/currentprice.json"
    );

    const data = await res.json();

    console.log(data);
    return data["bpi"][currency]["rate"];
}

export async function getStaticProps() {
    const res = await fetchBitcoinMetaData("USD");

    return {
        props: {
            name: res,
        },
    };
}
